package com.jjnford.android.util;

public class Shell {

	private Shell() {}

	/**
	 * Gain privileges to root shell.  Device must be rooted to use.
	 * 
	 * @return True if root shell is obtained, false if not.
	 */
	public static boolean su() {
		return false;
	}
	
	/**
	 * Execute a command in the root shell.  Devices must be rooted to use.
	 * 
	 * @param cmd The command to execute in root shell.
	 * @return True if command is executed successfully, false if not.
	 */
	public static boolean sudo(String cmd) {
		return false;
	}
	
	/**
	 * Execute a native shell command.
	 * 
	 * @param cmd The command to execute in the native shell.
	 * @return True if the command is executes successfully, false if not.
	 */
	public static boolean exec(String cmd) {
		return false;
	}
	
	/**
	 * Get the STDOUT output from the given command in the current shell.
	 * 
	 * @param cmd The command to execute and generate output.
	 * @return The output generated by the given command, null if none.
	 */
	public static String getOutput(String cmd) {
		return null;
	}
	
	/**
	 * Get the STDERR output from the given command in the current shell.
	 * 
	 * @param cmd The command to execute and generate output.
	 * @return The output generated by the given command, null if none.
	 */
	public static String getError(String cmd) {
		return null;
	}
}
